Release 0.4.0 - use subdomain as DNS name; tweak depends_on; new outputs
silinternational/terraform-aws-serverless-api-dns-for-failover pull request #9
Opened 2023-06-30 02:00 UTC by briskt

### Added
- New outputs: `primary_region_domain_name`, `primary_region_summary`, `secondary_region_domain_name`, and `secondary_region_summary`
 
### Changed
- Use only the subdomain when specifying the name of a DNS record. It works either way, but it seems the usual way is to not include the domain (zone). 
- Use the model name alone, not an output of the module for the `depends_on` in `module.domain`.

2023-07-06 12:29 UTC, Baggerone requested changes

2023-07-07 03:23 UTC, briskt commented on modules/fail-over-cname/outputs.tf
> +output "secondary_region_domain_name" {
Yes, thank you.

2023-07-07 12:12 UTC, Baggerone approved these changes

2023-07-07 12:12 UTC, Baggerone commented on modules/fail-over-cname/outputs.tf
> +output "secondary_region_domain_name" {
OK. I just fixed it here. (You fixed the other place.)

2023-07-10 12:55 UTC, merged